[package]
name = "FTPClient"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.52.0", features = ["rt-multi-thread", "macros", "net", "fs", "io-util"] }
serde = { version = "1.0.228", features = ["derive"] }
bytes = "1.11.1"
thiserror = "2.0.18" 
sha2 = "0.11.0"
hex = "0.4.3" 
clap = { version = "4.6.1", features = ["derive"]}